In [1]:
import numpy as npp

In [5]:
exam= npp.array([45,67,67,78])

In [6]:
exam

array([45, 67, 67, 78])

In [7]:
type(exam)

numpy.ndarray

In [8]:
ser=[34,'yu']

In [9]:
type(ser)

list

In [17]:
exam= npp.array([[45,67,67,78],[34,67,85,45],[1,1,1,1]])

In [18]:
exam

array([[45, 67, 67, 78],
       [34, 67, 85, 45],
       [ 1,  1,  1,  1]])

In [20]:
exam= npp.array([[[45,67,67,78],[34,67,85,45],[1,1,1,1]],[[45,67,67,78],[34,67,85,45],[1,1,1,1]]])

In [21]:
exam

array([[[45, 67, 67, 78],
        [34, 67, 85, 45],
        [ 1,  1,  1,  1]],

       [[45, 67, 67, 78],
        [34, 67, 85, 45],
        [ 1,  1,  1,  1]]])

In [23]:
zer=npp.zeros((4,4))

In [24]:
zer

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
one=npp.ones((3,3))
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [38]:
num=npp.random.rand(2,2)*1000

In [39]:
num

array([[206.17898289, 232.51737119],
       [986.84042553, 722.2606704 ]])

In [40]:
exam= npp.array([[[45,67,67,78],[34,67,85,45],[1,1,1,1]],[[45,67,67,78],[34,67,85,45],[1,1,1,1]]])

In [43]:
num.shape

(2, 2)

In [45]:
exam.size

24

In [46]:
exam.dtype

dtype('int64')

In [47]:
num.ndim

2

In [48]:
exam.ndim

3