In [24]:
import pandas as pd
s= pd.Series([1,2,3], index=['a','b','c'])

In [23]:
import pandas as pd

product_prices = pd.Series({
    "Apple": 50,
    "Banana": 20,
    "Orange": 30,
    "Mango": 80,
    "Grapes": 100
})

# Display the Series
print(product_prices)


Apple      50
Banana     20
Orange     30
Mango      80
Grapes    100
dtype: int64


In [6]:
product_prices.index
product_prices.values

array([ 50,  20,  30,  80, 100], dtype=int64)

In [7]:
product_prices.dtype

dtype('int64')

In [8]:
product_prices.shape

(5,)

In [9]:
product_prices.size

5

In [15]:
product_prices.empty

False

In [17]:
product_prices.nbytes

40

In [20]:
product_prices.is_unique

False

In [25]:
s.astype(float)

a    1.0
b    2.0
c    3.0
dtype: float64

In [26]:
s.to_list()

[1, 2, 3]

In [27]:
s.to_numpy()

array([1, 2, 3], dtype=int64)

In [28]:
s.to_dict()

{'a': 1, 'b': 2, 'c': 3}

In [29]:
s.loc['a']

1

In [33]:
s.iloc[0]

1

In [31]:
s.get('a', 0)

1

In [34]:
s.add(2)

a    3
b    4
c    5
dtype: int64

In [37]:
s.replace(1, 100)

a    100
b      2
c      3
dtype: int64

In [38]:
s.drop('a')

b    2
c    3
dtype: int64

In [39]:
s.count()

3

In [40]:
s.sum()

6

In [41]:
s.mean()

2.0

In [42]:
s.median()

2.0

In [43]:
s.std()

1.0

In [44]:
s.min()

1

In [45]:
s.max()

3

In [46]:
s.idxmin()

'a'

In [47]:
s.idxmax()

'c'

In [48]:
s.unique()

array([1, 2, 3], dtype=int64)

In [49]:
s.nunique()

3

In [50]:
s.value_counts()

1    1
2    1
3    1
Name: count, dtype: int64

In [ ]:
# Creating a Pandas DataFrame for employee records
employee_data = {
    "Employee_ID": [101, 102, 103, 104],
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Department": ["HR", "IT", "Finance", "Marketing"],
    "Salary": [50000, 70000, 60000, 65000]
}

df = pd.DataFrame(employee_data)

# Display the DataFrame
print(df)


In [52]:
data = {'A': [1, 2, 3], 'B': [4, 5, 6]}
df = pd.DataFrame(data)

In [53]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [54]:
df.columns

Index(['A', 'B'], dtype='object')

In [55]:
df.dtypes

A    int64
B    int64
dtype: object

In [56]:
df.shape

(3, 2)

In [ ]:
df.size

In [ ]:
df.empty

In [ ]:
df.ndim

In [ ]:
df.T

In [ ]:
pd.DataFrame(data)

In [ ]:
df.to_numpy()

In [ ]:
df.to_dict()

In [ ]:
df.to_csv('data.csv')

In [ ]:
df.to_excel('data.xlsx')

In [ ]:
df['A']

In [ ]:
df.loc[0, 'A']

In [ ]:
df.iloc[0, 0]

In [ ]:
df.at[0, 'A']

In [ ]:
df.iat[0, 0]

In [ ]:
df.drop(columns='A')

In [ ]:
df.drop(index=0)

In [ ]:
df.fillna(0)

In [ ]:
df.replace(1, 100)

In [ ]:
df.describe()

In [ ]:
df.count()

In [ ]:
df.mean()

In [ ]:
df.median()

In [ ]:
df.std()

In [ ]:
df.min()

In [ ]:
df.max()

In [ ]:
df['A'].value_counts()

In [ ]:
pd.concat([df, df])

In [ ]:
pd.merge(df, df, on='A')

In [ ]:
df.plot(kind='bar')

In [ ]:
df.plot(kind='line')